# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectsandInternships', models.CharField(max_length=200)),
                ('StudentId', models.IntegerField()),
                ('Branch', models.CharField(max_length=200)),
                ('PhoneNumber', models.IntegerField()),
                ('Cgpa', models.FloatField()),
                ('TenthMarks', models.FloatField()),
                ('TenthSchoolName', models.CharField(max_length=200)),
                ('TwelthMarks', models.FloatField()),
                ('TwelthCollegeName', models.CharField(max_length=200)),
                ('StudentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
